flat_teaching.Rmd:
  path: dev/flat_teaching.Rmd
  state: active
  R: R/add_one.R
  tests: tests/testthat/test-add_one.R
  vignettes: vignettes/basic-usage.Rmd
  inflate:
    flat_file: dev/flat_teaching.Rmd
    vignette_name: Basic Usage
    open_vignette: true
    check: true
    document: true
    overwrite: ask
